### ISSUE TITLE
Merging parameter/statefulparameter/functions/derivedvariable to one entity 

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#101]
As an option to resolve the state/stateful_parameter discussions, one option would be to merge all of the different features in these to one entity (probably best called parameter...) which can either be:
- a constant (like old parameters), 
- evaluated by an inbuilt function (like "function"/derived variable)
- be evaluated by a freeform expression (as was proposed for "function"/derived variable)
- have a simple statelike update rule (like state/stateful parameter)
- have a time derivative (like state)

The conversion from MDF to MDFzero would involve finding the ones with time derivatives, adding dt as a parameter and converting them to simple stateful parameters

Working on this here: https://github.com/ModECI/MDF/tree/parameter_state_merge, e.g.
```
graphs:
        state_example:
            nodes:
                counter_node:
                    parameters:
                        increment:
                            value: '1'
                        count:
                            value: count + increment
                    output_ports:
                        out_port:
                            value: count
                sine_node:
                    parameters:
                        amp:
                            value: '3'
                        period:
                            value: '0.4'
                        level:
                            default_initial_value: '0'
                            time_derivative: 6.283185 * rate / period
                        rate:
                            default_initial_value: '1'
                            time_derivative: -1 * 6.283185 * level / period
                    output_ports:
                        out_port:
                            value: amp * level
```
