### ISSUE TITLE
Add conditional evaluation to parameters

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#184]
This will be required for many neuroscience models (e.g. spiking cell should reset membrane potential if it passes threshold, but use time derivative for all other times) and in general for models in other domains

Requirements

- set a parameter to a specific value if a certain condition is met
- limited to parameter values in current state of node
- the value when a test evaluates as true overrides other values/time derivatives/functions
- multiple conditions can be set on one parameter, and they should be tested in turn

**Comment by pgleeson** [comment]
Being worked on here: https://github.com/ModECI/MDF/tree/nml_examples
e.g. [here](https://github.com/ModECI/MDF/blob/nml_examples/examples/MDF/RNN/IAFs.yaml)
```
    iaf_node:
        input_ports:
            input: {}
        parameters:
            erev:
                value: -70
            tau:
                value: 10
            thresh:
                value: -20
            v:
                default_initial_value: '-50'
                time_derivative: -1 * (v-erev)/tau + input
                conditions:
                    reset:
                        test: v > thresh
                        value: erev
```
![image](https://user-images.githubusercontent.com/1556687/145090488-aa6bf949-6b66-4040-ae63-fa16b0b32fc4.png)

leads to 

<img width="647" alt="Screenshot 2021-12-07 at 19 06 58" src="https://user-images.githubusercontent.com/1556687/145090683-fd068895-da0a-4c45-872c-e9f0b4e986f4.png">
